
* TODO Special cases

Org, among others, use dedicated functions to traverse certain
objects, eg =org-forward-sentence=.  Divine motions should use these
functions when applicable, either by checking for =remap=s in keymaps,
or manually.

* TODO Work on *two* regions

Emacs has primary and secondary selections, so commands like swap,
etc, could also work on both selections.

* TODO Normal mode for major/minor modes

It's probably extremely useful to be able to create mode-specific
normal bindings.  A simple solution would be to create a set
`divine-normal-MODE-mode-map` that modes toggle.  See how selected
does it.

* TODO Simplify binding system

To simplify context-dependent bindings (eg "a", which is append unless
Divine is pending operator, in which case it's "around"), let's just
bind everything to a single function, divine-special-binding, and
create a macro (divine-conditional-binding or something) in which this
function can call)

* TODO Fragile activation

Instead of transient activation, create a fragile activation for prefixes that uses read-char on the target mode map only once.

* TODO Create special modes and maps

 - For when the region is active.
 - For when numeric argument is non-nil.

* TODO Generalize scopes

The implicit assumption that scopes only apply to text objects is
limited. (What did I mean here?)

* TODO Support repeated insertion?

Vim can do COUNT i {type something} ESC.

* DONE Restore cursor on abort

Pressing C-g on (divine-read-char) doesn't cleanup after itself. We
need to hook for that.
